services:
  frontend:
    container_name: dateIdeas.Frontend
    build: ./DateIdeas.Frontend
    ports:
      - "3000:3000"  # Expose Nginx on port 80
    environment:
      - BACKEND_URL=${BACKEND_URL}  # Use the service name 'backend' in the URL
    networks:
      - app-network

  backend:
    container_name: dateIdeas.Backend
    build: ./DateIdeas.Backend
    ports:
      - "5500:5000"  # Ensure the backend is accessible on port 5000
    environment:
      - FRONTEND_URL=${FRONTEND_URL}  # Use the service name 'backend' in the URL
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY} # Get the Google Maps API key from the environment
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_EMAIL=${FROM_EMAIL}
      - REQUIRE_CONFIRM_EMAIL=${REQUIRE_CONFIRM_EMAIL}
    networks:
      - app-network
    volumes:
      # - /Users/joseph/Documents/dateIdeas.Backend:/data # Mac
      # - C:\Users\Joseph\Documents\dateIdeas.Backend:/data # Windows
      - /home/debian/docker/config/dateideas.backend:/data # Linux

networks:
  app-network:
    driver: bridge
